### ISSUE TITLE
Odd behavior with docker

### ISSUE THREAD

**Issue by Yey007** [sidorares/node-mysql2#1245]
Hello,

Please let me know if you think this does not fall under your domain.
I'm attempting to connect to a mysql database running in docker, with my app also running in docker. They are ran together using docker-compose. If I try to connect to the database using this library, it seems to always attempt to use the wrong IP address, and I get a connection refused error. For example, when I pass "db" as the host like this:

```
let conn = createConnection({
    host: "db",
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: process.env.MYSQL_DATABASE
});
```
It gives the error `Error: connect ECONNREFUSED 127.0.0.1:3306` (note `127.0.0.1`). I also tried resolving "db" and using that address:

```
let conn = createConnection({
    host: "192.168.80.2",
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: process.env.MYSQL_DATABASE
});
```

But got the same error. I am 99% sure all of my environment variable are correct and that the mysql container is running when it attempts to connect (it always restarts the container)

Here is my docker-compsose file:
```
version: "3.8"

services: 
  bot:
    container_name: bot
    image: yey007/transcriberbot:latest
    depends_on: 
      - db
    env_file:
      - .env
    restart: always
    networks:
      - my_network
  
  db:
    container_name: database
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file: 
      - db.env
    restart: always
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
```

Again, please let me know if this doesn't fall under your domain. I've troubleshooted a lot and am pretty sure I haven't severely messed anything up, so I came to ask here. Thank you!

**Comment by sidorares** [comment]
from the driver point of view whatever is in `host` and `port` parameters passes to `net.connect()` - https://nodejs.org/api/net.html#net_socket_connect_port_host_connectlistener

can you ssh into `bot` container and check network manually? ( what ip address host is resolved, can you telnet to that port/ip)

**Comment by Yey007** [comment]
If I connect using `let socket = net.connect(3306, "db", () => {console.log("connected")})`, the resulting socket looks like this:

```
<ref *1> Socket {
  connecting: false,
  _hadError: false,
  _parent: null,
  _host: 'db',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: [Object], tail: [Object], length: 1 },
    length: 78,
    pipes: [],
    flowing: null,
    ended: true,
    endEmitted: false,
    reading: false,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 874,
  [Symbol(kHandle)]: TCP {
    reading: true,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
```

Looking up the address using `dns.lookup("db", (err, ip) => {console.log(ip)})` yields `172.23.0.2`

If I run `nc db 3306` (not quite telnet), I get this response: 
```
J
8.0.22  cb7NJ1`l���☻��§j]T6@q=%xP|7mysql_native_password
```
Which looks like a proper response from the server (with some stuff jumbled in, idk if that's supposed to be there but it's probably just binary data or something.)

**Comment by Yey007** [comment]
A couple more things to note:
1. `nslookup` resolves the host properly as well
2. I've been having more weird behavior with the library occasionally selecting the right ip, yet still failing to connect. 
3. Passing the correct ip instead of "db" doesn't yield better results.

**Comment by Yey007** [comment]
I have solved the problem! The issue was the db wasn't ready yet, and putting the connection in a simple timeout worked. This is odd, however, as I had this in a restart loop (through docker-compose) before so it should've been able to connect eventually. Weird.
